/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

export const GOOGLE_API_KEY = 'AIzaSyCo7G_rujOcNZsyh3K6aSUTYfYkCHKPXWI';

const awsmobile = {
	aws_project_region: 'us-west-2',
	aws_cognito_identity_pool_id:
		'us-west-2:d2ad4c03-21f3-4a2d-9b1e-f640b369ed02',
	aws_cognito_region: 'us-west-2',
	aws_user_pools_id: 'us-west-2_F7CJv3cj9',
	aws_user_pools_web_client_id: '798ua2rk9tgghs8dr69fv3vvkb',
	oauth: {
		domain: 'nombolo-oauth-prod.auth.us-west-2.amazoncognito.com',
		scope: [
			'phone',
			'email',
			'openid',
			'profile',
			'aws.cognito.signin.user.admin',
		],
		redirectSignIn: 'nomboloscheme://',
		redirectSignOut: 'nomboloscheme://',
		responseType: 'code',
	},
	federationTarget: 'COGNITO_USER_AND_IDENTITY_POOLS',
	aws_appsync_graphqlEndpoint:
		'https://4c37p77xmvcvrbckj3qq3q23te.appsync-api.us-west-2.amazonaws.com/graphql',
	aws_appsync_region: 'us-west-2',
	aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
	aws_user_files_s3_bucket: 'nombolo-s3-bucket120302-prod',
	aws_user_files_s3_bucket_region: 'us-west-2',
	aws_mobile_analytics_app_id: '847c2f8200214665921de3f5a1907be3',
	aws_mobile_analytics_app_region: 'us-west-2',
};

export default awsmobile;
